name: plant_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_database: ^11.3.10
  flutter_bloc: ^9.1.1
  build_runner: ^2.4.14
  json_serializable: ^6.9.5
  flutter_screenutil: ^5.9.3
  flutter_hooks: ^0.21.2
  toastification: ^3.0.3
  json_annotation: ^4.9.0
  shorebird_code_push: ^2.0.4
  sliding_clipped_nav_bar: ^3.1.1
  flutter_snake_navigationbar: ^0.6.1
  dot_navigation_bar: ^1.0.2
  smooth_page_indicator: ^1.2.1
  page_view_dot_indicator: ^2.3.0
  icons_launcher: ^3.0.1
  flutter_phoenix: ^1.1.1
  restart_app: ^1.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  keyboard_avoider: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - shorebird.yaml
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
 
